<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Admin-PC" failures="2" tests="4" name="login.authentication" time="8.146" errors="0" timestamp="2024-03-12T23:17:35 GMT+07:00" skipped="0">
  <testcase classname="login.authentication" name="TC_01_getUrl" time="0.012">
    <failure message="expected [https://cntttest.vanlanguni.edu.vn:18081/Phancong02/] but found [https://login.microsoftonline.com/common/SAS/ProcessAuth]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://cntttest.vanlanguni.edu.vn:18081/Phancong02/] but found [https://login.microsoftonline.com/common/SAS/ProcessAuth]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at login.authentication.TC_01_getUrl(authentication.java:60)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_01_getUrl -->
  <system-out/>
  <testcase classname="login.authentication" name="TC_02_getCookies" time="0.046"/>
  <system-out/>
  <testcase classname="login.authentication" name="TC_04_useCookies" time="4.828">
    <failure message="expected [https://cntttest.vanlanguni.edu.vn:18081/Phancong02/] but found [https://login.microsoftonline.com/3011a54b-0a5d-4929-bf02-a00787877c6a/oauth2/v2.0/authorize?client_id=67282914-bf53-41a1-9ebf-45af2f051111&amp;response_type=code%20id_token&amp;scope=openid%20profile&amp;state=OpenIdConnect.AuthenticationProperties%3DVM252qHFbE6LHmq-x2bM4SKYcJay4pra7FJ3CoFV-0wIBuZThByiCDZ6TO1UMxxI8_11jPnq4hJjaemkwBKQVoQNKyX8jN99NHdGuwf64m9pmWMSxJVIIcIm270ZomrTZ5mY7ueOT0Rz9xB_m0wPOA&amp;response_mode=form_post&amp;nonce=638458569864667097.NmQ5OGNhNDAtNmZmYi00OWJjLWJjNDktMzg1MWU4NmQ3OThhZGI0NDYwZjUtODI1Zi00ZTgwLThlOGYtN2ViZGYwNTg0Njg4&amp;x-client-SKU=ID_NET472&amp;x-client-ver=6.32.0.0&amp;sso_reload=true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://cntttest.vanlanguni.edu.vn:18081/Phancong02/] but found [https://login.microsoftonline.com/3011a54b-0a5d-4929-bf02-a00787877c6a/oauth2/v2.0/authorize?client_id=67282914-bf53-41a1-9ebf-45af2f051111&response_type=code%20id_token&scope=openid%20profile&state=OpenIdConnect.AuthenticationProperties%3DVM252qHFbE6LHmq-x2bM4SKYcJay4pra7FJ3CoFV-0wIBuZThByiCDZ6TO1UMxxI8_11jPnq4hJjaemkwBKQVoQNKyX8jN99NHdGuwf64m9pmWMSxJVIIcIm270ZomrTZ5mY7ueOT0Rz9xB_m0wPOA&response_mode=form_post&nonce=638458569864667097.NmQ5OGNhNDAtNmZmYi00OWJjLWJjNDktMzg1MWU4NmQ3OThhZGI0NDYwZjUtODI1Zi00ZTgwLThlOGYtN2ViZGYwNTg0Njg4&x-client-SKU=ID_NET472&x-client-ver=6.32.0.0&sso_reload=true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at login.authentication.TC_04_useCookies(authentication.java:135)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_04_useCookies -->
  <system-out/>
  <testcase classname="login.authentication" name="TC_03_logout" time="3.260"/>
  <system-out/>
</testsuite> <!-- login.authentication -->
